select * from customer limit 20;

--01. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--02. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount) FROM customer
);

--03 Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(NULLIF(TRIM(review_rating),'')::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY "Average Product Rating" DESC
LIMIT 5;

--04. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
	Round(AVG(purchase_amount),2)
from customer
where LOWER(TRIM(shipping_type)) in ('standard','express')
group by shipping_type

--05. Do subscribed customers spend more? Compare average spend and 
-- total revenue between subscribers and non-subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spent,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spent desc;

--06. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(
    AVG(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END) * 100, 2
) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their 
-- total number of previous purchases, and show count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc; 







