select * from customer limit 20;

--01. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--02. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'yes'
AND purchase_amount >= (
    SELECT AVG(purchase_amount) FROM customer
);

--03 Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by "Average Product Rating" desc
limit 5;

--04. Compare the average Purchase Amounts between Standard and Express Shipping.
--05. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-su
--06. Which 5 products have the highest percentage of purchases with discounts applied?
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and sh
--Q8. What are the top 3 most purchased products within each category?
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group?







